name: flutter_nexus
description: Nexus - Geo-Contextual News Platform
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  supabase_flutter: ^2.8.0
  url_launcher: ^6.3.0
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces-Variable.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Variable.ttf
