// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/comments" | "/admin/journalists" | "/admin/metrics" | "/admin/quiz" | "/admin/sources" | "/admin/subscriptions" | "/admin/users" | "/admin/users/[userId]" | "/article/[id]" | "/country/[code]" | "/crossword" | "/digest" | "/feed" | "/journalist/[id]" | "/leaderboard" | "/login" | "/onboarding" | "/premium" | "/profile" | "/quiz" | "/search"
type AppRouteHandlerRoutes = "/api/cron/fetch-news" | "/api/v1/admin/comments" | "/api/v1/admin/comments/[commentId]" | "/api/v1/admin/journalists" | "/api/v1/admin/journalists/[journalistId]" | "/api/v1/admin/metrics" | "/api/v1/admin/quiz" | "/api/v1/admin/quiz/[quizId]" | "/api/v1/admin/sources" | "/api/v1/admin/sources/[sourceId]" | "/api/v1/admin/subscriptions" | "/api/v1/admin/users" | "/api/v1/admin/users/[userId]" | "/api/v1/admin/users/[userId]/activity" | "/api/v1/admin/users/[userId]/sessions" | "/api/v1/articles" | "/api/v1/articles/[id]" | "/api/v1/articles/[id]/comments" | "/api/v1/articles/[id]/comments/[commentId]" | "/api/v1/articles/[id]/reactions" | "/api/v1/articles/[id]/view" | "/api/v1/auth/callback" | "/api/v1/auth/change-password" | "/api/v1/auth/check-email" | "/api/v1/auth/otp" | "/api/v1/auth/session" | "/api/v1/auth/signout" | "/api/v1/crossword" | "/api/v1/crossword/submit" | "/api/v1/digest" | "/api/v1/feed" | "/api/v1/feed/breaking" | "/api/v1/internal/fetch-news" | "/api/v1/internal/generate-digest" | "/api/v1/internal/generate-quizzes" | "/api/v1/journalist/posts" | "/api/v1/journalist/posts/[id]" | "/api/v1/journalist/posts/[id]/comments" | "/api/v1/journalist/posts/[id]/comments/[commentId]" | "/api/v1/journalist/posts/[id]/reactions" | "/api/v1/journalist/profile" | "/api/v1/journalists/[id]" | "/api/v1/journalists/[id]/follow" | "/api/v1/leaderboard" | "/api/v1/quiz/general" | "/api/v1/quiz/general/submit" | "/api/v1/quiz/submit" | "/api/v1/quiz/today" | "/api/v1/regions" | "/api/v1/search" | "/api/v1/stripe/checkout" | "/api/v1/stripe/verify-session" | "/api/v1/stripe/webhook" | "/api/v1/trending" | "/api/v1/user/avatar" | "/api/v1/user/bookmarks" | "/api/v1/user/preferences" | "/api/v1/user/profile" | "/api/v1/user/sessions" | "/api/v1/user/sessions/[sessionId]" | "/api/v1/user/stats" | "/api/v1/user/subscription"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/comments": {}
  "/admin/journalists": {}
  "/admin/metrics": {}
  "/admin/quiz": {}
  "/admin/sources": {}
  "/admin/subscriptions": {}
  "/admin/users": {}
  "/admin/users/[userId]": { "userId": string; }
  "/api/cron/fetch-news": {}
  "/api/v1/admin/comments": {}
  "/api/v1/admin/comments/[commentId]": { "commentId": string; }
  "/api/v1/admin/journalists": {}
  "/api/v1/admin/journalists/[journalistId]": { "journalistId": string; }
  "/api/v1/admin/metrics": {}
  "/api/v1/admin/quiz": {}
  "/api/v1/admin/quiz/[quizId]": { "quizId": string; }
  "/api/v1/admin/sources": {}
  "/api/v1/admin/sources/[sourceId]": { "sourceId": string; }
  "/api/v1/admin/subscriptions": {}
  "/api/v1/admin/users": {}
  "/api/v1/admin/users/[userId]": { "userId": string; }
  "/api/v1/admin/users/[userId]/activity": { "userId": string; }
  "/api/v1/admin/users/[userId]/sessions": { "userId": string; }
  "/api/v1/articles": {}
  "/api/v1/articles/[id]": { "id": string; }
  "/api/v1/articles/[id]/comments": { "id": string; }
  "/api/v1/articles/[id]/comments/[commentId]": { "id": string; "commentId": string; }
  "/api/v1/articles/[id]/reactions": { "id": string; }
  "/api/v1/articles/[id]/view": { "id": string; }
  "/api/v1/auth/callback": {}
  "/api/v1/auth/change-password": {}
  "/api/v1/auth/check-email": {}
  "/api/v1/auth/otp": {}
  "/api/v1/auth/session": {}
  "/api/v1/auth/signout": {}
  "/api/v1/crossword": {}
  "/api/v1/crossword/submit": {}
  "/api/v1/digest": {}
  "/api/v1/feed": {}
  "/api/v1/feed/breaking": {}
  "/api/v1/internal/fetch-news": {}
  "/api/v1/internal/generate-digest": {}
  "/api/v1/internal/generate-quizzes": {}
  "/api/v1/journalist/posts": {}
  "/api/v1/journalist/posts/[id]": { "id": string; }
  "/api/v1/journalist/posts/[id]/comments": { "id": string; }
  "/api/v1/journalist/posts/[id]/comments/[commentId]": { "id": string; "commentId": string; }
  "/api/v1/journalist/posts/[id]/reactions": { "id": string; }
  "/api/v1/journalist/profile": {}
  "/api/v1/journalists/[id]": { "id": string; }
  "/api/v1/journalists/[id]/follow": { "id": string; }
  "/api/v1/leaderboard": {}
  "/api/v1/quiz/general": {}
  "/api/v1/quiz/general/submit": {}
  "/api/v1/quiz/submit": {}
  "/api/v1/quiz/today": {}
  "/api/v1/regions": {}
  "/api/v1/search": {}
  "/api/v1/stripe/checkout": {}
  "/api/v1/stripe/verify-session": {}
  "/api/v1/stripe/webhook": {}
  "/api/v1/trending": {}
  "/api/v1/user/avatar": {}
  "/api/v1/user/bookmarks": {}
  "/api/v1/user/preferences": {}
  "/api/v1/user/profile": {}
  "/api/v1/user/sessions": {}
  "/api/v1/user/sessions/[sessionId]": { "sessionId": string; }
  "/api/v1/user/stats": {}
  "/api/v1/user/subscription": {}
  "/article/[id]": { "id": string; }
  "/country/[code]": { "code": string; }
  "/crossword": {}
  "/digest": {}
  "/feed": {}
  "/journalist/[id]": { "id": string; }
  "/leaderboard": {}
  "/login": {}
  "/onboarding": {}
  "/premium": {}
  "/profile": {}
  "/quiz": {}
  "/search": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
