// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/comments">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/journalist-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/journalist-requests">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/journalist-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/journalists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/journalists">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/journalists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/metrics">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/quiz">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sources">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/users/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/users/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/article/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/article/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/article/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/country/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/country/[code]">> = Specific
  const handler = {} as typeof import("../../../../src/app/country/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/crossword/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crossword">> = Specific
  const handler = {} as typeof import("../../../../src/app/crossword/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feed">> = Specific
  const handler = {} as typeof import("../../../../src/app/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/journalist/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/journalist/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/journalist/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/premium/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium">> = Specific
  const handler = {} as typeof import("../../../../src/app/premium/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quiz">> = Specific
  const handler = {} as typeof import("../../../../src/app/quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../../src/app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/cron/fetch-news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/fetch-news">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/cron/fetch-news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/comments">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/journalist-requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/journalist-requests/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/journalist-requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/journalist-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/journalist-requests">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/journalist-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/journalists/[journalistId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/journalists/[journalistId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/journalists/[journalistId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/journalists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/journalists">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/journalists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/metrics">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/posts/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/posts">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/quiz/[quizId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/quiz/[quizId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/quiz/[quizId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/quiz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/quiz">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/quiz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/sources/[sourceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/sources/[sourceId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/sources/[sourceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/sources">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/users/[userId]/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/users/[userId]/activity">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/users/[userId]/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/users/[userId]/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/users/[userId]/sessions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/users/[userId]/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/users">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/articles/[id]/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/articles/[id]/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/articles/[id]/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/articles/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/articles/[id]/comments">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/articles/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/articles/[id]/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/articles/[id]/reactions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/articles/[id]/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/articles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/articles/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/articles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/articles/[id]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/articles/[id]/view">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/articles/[id]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/articles">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/callback">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/change-password">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/auth/check-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/check-email">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/auth/check-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/auth/otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/otp">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/auth/otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/session">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/signout">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/crossword/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/crossword">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/crossword/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/crossword/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/crossword/submit">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/crossword/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/feed/breaking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/feed/breaking">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/feed/breaking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/feed">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/internal/fetch-news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/internal/fetch-news">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/internal/fetch-news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/internal/generate-quizzes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/internal/generate-quizzes">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/internal/generate-quizzes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalist/posts/[id]/bookmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalist/posts/[id]/bookmark">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalist/posts/[id]/bookmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalist/posts/[id]/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalist/posts/[id]/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalist/posts/[id]/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalist/posts/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalist/posts/[id]/comments">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalist/posts/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalist/posts/[id]/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalist/posts/[id]/reactions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalist/posts/[id]/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalist/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalist/posts/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalist/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalist/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalist/posts">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalist/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalist/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalist/profile">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalist/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalists/[id]/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalists/[id]/follow">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalists/[id]/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/journalists/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/journalists/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/journalists/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/leaderboard">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/quiz/general/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/quiz/general">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/quiz/general/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/quiz/general/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/quiz/general/submit">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/quiz/general/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/quiz/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/quiz/submit">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/quiz/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/quiz/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/quiz/today">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/quiz/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/regions/[slug]/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/regions/[slug]/articles">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/regions/[slug]/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/regions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/regions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/regions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/search">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/stripe/verify-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/stripe/verify-session">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/stripe/verify-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/trending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/trending">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/trending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/avatar">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/bookmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/bookmarks">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/bookmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/journalist-request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/journalist-request">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/journalist-request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/notifications/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/notifications/read">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/notifications/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/notifications">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/preferences">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/profile">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/sessions/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/sessions/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/sessions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/stats">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/v1/user/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/user/subscription">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/v1/user/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
